# 停用服务端口
spring:
  main:
    web-environment: false
# kafka
  kafka:
    bootstrap-servers: localhost:9092
    topic: binlog
    partNum: 3
    repeatNum: 1
# binlog配置 linux版
server:
  id: 1
binlog:
  host: 129.211.113.218
  port: 3306
  user: root
  password: Pass12345
# 指定监听的表格
  database:
    table: project.user,project.role

## binlog配置 windows版
#server.id=1
#binlog.host=localhost
#binlog.port=3306
#binlog.user=root
#binlog.password=Pass12345
## 指定监听的表格
#binlog.database.table=project.user,project.role




